version: '3.7'

services:
    backend:
        build:
          context: ./simple-api
          dockerfile: Dockerfile
        container_name: backendtp
        networks:
        - app-network
        depends_on: 
        - database

    database:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: databasetp
        networks:
        - app-network

    httpd:
        build:
          context: ./httpserver
          dockerfile: Dockerfile
        container_name: fronttp
        ports:
        - "80:80"
        networks:
        - app-network
        depends_on:
        - backend

    front:
        build:
          context: ./front
          dockerfile: Dockerfile
        container_name: front
        ports:
        - "8081:80"
        networks:
        - app-network
        depends_on:
        - httpd

networks:
    app-network: 
